name: Puppeteer Automation

on:
  schedule:
    - cron: "0 0 * * *"
  push:
    branches:
      - main
jobs:
  puppeteer_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm install

      - name: Run Puppeteer script
        run: |
          cd data
          xvfb-run --server-args="-screen 0 1024x768x24" node script.js

      - name: Commit and push changes
        run: |
          git config --global user.name "luizfelipemacedoc"
          git config --global user.email "114022960+luizfelipemacedoc@users.noreply.github.com"
          git add data/products.json
          git commit -m "Update products.json"
          git push origin main
